/* eslint-disable import/no-anonymous-default-export */
export default {
  data: [
    {
      zip: "30002",
      city: "Avondale Estates",
      county: "Dekalb",
      pop: 6054,
    },
    {
      zip: "30004",
      city: "Alpharetta",
      county: "Fulton",
      pop: 65294,
    },
    {
      zip: "30005",
      city: "Alpharetta",
      county: "Fulton",
      pop: 39420,
    },
    {
      zip: "30008",
      city: "Marietta",
      county: "Cobb",
      pop: 33637,
    },
    {
      zip: "30009",
      city: "Alpharetta",
      county: "Fulton",
      pop: 17371,
    },
    {
      zip: "30011",
      city: "Auburn",
      county: "Barrow",
      pop: 15806,
    },
    {
      zip: "30012",
      city: "Conyers",
      county: "Rockdale",
      pop: 28591,
    },
    {
      zip: "30013",
      city: "Conyers",
      county: "Rockdale",
      pop: 26555,
    },
    {
      zip: "30014",
      city: "Covington",
      county: "Newton",
      pop: 38041,
    },
    {
      zip: "30016",
      city: "Covington",
      county: "Newton",
      pop: 55279,
    },
    {
      zip: "30017",
      city: "Grayson",
      county: "Gwinnett",
      pop: 23415,
    },
    {
      zip: "30019",
      city: "Dacula",
      county: "Gwinnett",
      pop: 48782,
    },
    {
      zip: "30021",
      city: "Clarkston",
      county: "Dekalb",
      pop: 23493,
    },
    {
      zip: "30022",
      city: "Alpharetta",
      county: "Fulton",
      pop: 68945,
    },
    {
      zip: "30024",
      city: "Suwanee",
      county: "Gwinnett",
      pop: 79000,
    },
    {
      zip: "30025",
      city: "Social Circle",
      county: "Walton",
      pop: 9679,
    },
    {
      zip: "30028",
      city: "Cumming",
      county: "Forsyth",
      pop: 27120,
    },
    {
      zip: "30030",
      city: "Decatur",
      county: "Dekalb",
      pop: 30608,
    },
    {
      zip: "30032",
      city: "Decatur",
      county: "Dekalb",
      pop: 47980,
    },
    {
      zip: "30033",
      city: "Decatur",
      county: "Dekalb",
      pop: 32847,
    },
    {
      zip: "30034",
      city: "Decatur",
      county: "Dekalb",
      pop: 48253,
    },
    {
      zip: "30035",
      city: "Decatur",
      county: "Dekalb",
      pop: 23223,
    },
    {
      zip: "30038",
      city: "Lithonia",
      county: "Dekalb",
      pop: 39514,
    },
    {
      zip: "30039",
      city: "Snellville",
      county: "Gwinnett",
      pop: 47778,
    },
    {
      zip: "30040",
      city: "Cumming",
      county: "Forsyth",
      pop: 72909,
    },
    {
      zip: "30041",
      city: "Cumming",
      county: "Forsyth",
      pop: 69117,
    },
    {
      zip: "30043",
      city: "Lawrenceville",
      county: "Gwinnett",
      pop: 91378,
    },
    {
      zip: "30044",
      city: "Lawrenceville",
      county: "Gwinnett",
      pop: 89139,
    },
    {
      zip: "30045",
      city: "Lawrenceville",
      county: "Gwinnett",
      pop: 43018,
    },
    {
      zip: "30046",
      city: "Lawrenceville",
      county: "Gwinnett",
      pop: 37338,
    },
    {
      zip: "30047",
      city: "Lilburn",
      county: "Gwinnett",
      pop: 65937,
    },
    {
      zip: "30052",
      city: "Loganville",
      county: "Gwinnett",
      pop: 68563,
    },
    {
      zip: "30054",
      city: "Oxford",
      county: "Newton",
      pop: 12318,
    },
    {
      zip: "30055",
      city: "Mansfield",
      county: "Jasper",
      pop: 3432,
    },
    {
      zip: "30056",
      city: "Newborn",
      county: "Newton",
      pop: 2262,
    },
    {
      zip: "30058",
      city: "Lithonia",
      county: "Dekalb",
      pop: 59751,
    },
    {
      zip: "30060",
      city: "Marietta",
      county: "Cobb",
      pop: 40290,
    },
    {
      zip: "30062",
      city: "Marietta",
      county: "Cobb",
      pop: 65801,
    },
    {
      zip: "30064",
      city: "Marietta",
      county: "Cobb",
      pop: 49256,
    },
    {
      zip: "30066",
      city: "Marietta",
      county: "Cobb",
      pop: 55937,
    },
    {
      zip: "30067",
      city: "Marietta",
      county: "Cobb",
      pop: 46536,
    },
    {
      zip: "30068",
      city: "Marietta",
      county: "Cobb",
      pop: 32453,
    },
    {
      zip: "30070",
      city: "Porterdale",
      county: "Newton",
      pop: 426,
    },
    {
      zip: "30071",
      city: "Norcross",
      county: "Gwinnett",
      pop: 25386,
    },
    {
      zip: "30072",
      city: "Pine Lake",
      county: "Dekalb",
      pop: 730,
    },
    {
      zip: "30075",
      city: "Roswell",
      county: "Fulton",
      pop: 53779,
    },
    {
      zip: "30076",
      city: "Roswell",
      county: "Fulton",
      pop: 46742,
    },
    {
      zip: "30078",
      city: "Snellville",
      county: "Gwinnett",
      pop: 35601,
    },
    {
      zip: "30079",
      city: "Scottdale",
      county: "Dekalb",
      pop: 3973,
    },
    {
      zip: "30080",
      city: "Smyrna",
      county: "Cobb",
      pop: 57067,
    },
    {
      zip: "30082",
      city: "Smyrna",
      county: "Cobb",
      pop: 27840,
    },
    {
      zip: "30083",
      city: "Stone Mountain",
      county: "Dekalb",
      pop: 57137,
    },
    {
      zip: "30084",
      city: "Tucker",
      county: "Dekalb",
      pop: 38374,
    },
    {
      zip: "30087",
      city: "Stone Mountain",
      county: "Dekalb",
      pop: 39586,
    },
    {
      zip: "30088",
      city: "Stone Mountain",
      county: "Dekalb",
      pop: 30132,
    },
    {
      zip: "30092",
      city: "Norcross",
      county: "Gwinnett",
      pop: 36034,
    },
    {
      zip: "30093",
      city: "Norcross",
      county: "Gwinnett",
      pop: 56290,
    },
    {
      zip: "30094",
      city: "Conyers",
      county: "Rockdale",
      pop: 33579,
    },
    {
      zip: "30096",
      city: "Duluth",
      county: "Gwinnett",
      pop: 68691,
    },
    {
      zip: "30097",
      city: "Duluth",
      county: "Gwinnett",
      pop: 46609,
    },
    {
      zip: "30101",
      city: "Acworth",
      county: "Cobb",
      pop: 59515,
    },
    {
      zip: "30102",
      city: "Acworth",
      county: "Cobb",
      pop: 42278,
    },
    {
      zip: "30103",
      city: "Adairsville",
      county: "Bartow",
      pop: 15787,
    },
    {
      zip: "30104",
      city: "Aragon",
      county: "Polk",
      pop: 5136,
    },
    {
      zip: "30105",
      city: "Armuchee",
      county: "Floyd",
      pop: 1781,
    },
    {
      zip: "30106",
      city: "Austell",
      county: "Cobb",
      pop: 21718,
    },
    {
      zip: "30107",
      city: "Ball Ground",
      county: "Cherokee",
      pop: 13517,
    },
    {
      zip: "30108",
      city: "Bowdon",
      county: "Carroll",
      pop: 7755,
    },
    {
      zip: "30110",
      city: "Bremen",
      county: "Haralson",
      pop: 13835,
    },
    {
      zip: "30113",
      city: "Buchanan",
      county: "Haralson",
      pop: 6273,
    },
    {
      zip: "30114",
      city: "Canton",
      county: "Cherokee",
      pop: 54709,
    },
    {
      zip: "30115",
      city: "Canton",
      county: "Cherokee",
      pop: 42934,
    },
    {
      zip: "30116",
      city: "Carrollton",
      county: "Carroll",
      pop: 25169,
    },
    {
      zip: "30117",
      city: "Carrollton",
      county: "Carroll",
      pop: 35620,
    },
    {
      zip: "30118",
      city: "Carrollton",
      county: "Carroll",
      pop: 2096,
    },
    {
      zip: "30120",
      city: "Cartersville",
      county: "Bartow",
      pop: 40945,
    },
    {
      zip: "30121",
      city: "Cartersville",
      county: "Bartow",
      pop: 24742,
    },
    {
      zip: "30122",
      city: "Lithia Springs",
      county: "Douglas",
      pop: 26015,
    },
    {
      zip: "30124",
      city: "Cave Spring",
      county: "Floyd",
      pop: 2980,
    },
    {
      zip: "30125",
      city: "Cedartown",
      county: "Polk",
      pop: 24052,
    },
    {
      zip: "30126",
      city: "Mableton",
      county: "Cobb",
      pop: 43486,
    },
    {
      zip: "30127",
      city: "Powder Springs",
      county: "Cobb",
      pop: 70298,
    },
    {
      zip: "30132",
      city: "Dallas",
      county: "Paulding",
      pop: 42607,
    },
    {
      zip: "30134",
      city: "Douglasville",
      county: "Douglas",
      pop: 43402,
    },
    {
      zip: "30135",
      city: "Douglasville",
      county: "Douglas",
      pop: 67710,
    },
    {
      zip: "30137",
      city: "Emerson",
      county: "Bartow",
      pop: 1914,
    },
    {
      zip: "30139",
      city: "Fairmount",
      county: "Gordon",
      pop: 3940,
    },
    {
      zip: "30141",
      city: "Hiram",
      county: "Paulding",
      pop: 23733,
    },
    {
      zip: "30143",
      city: "Jasper",
      county: "Pickens",
      pop: 23206,
    },
    {
      zip: "30144",
      city: "Kennesaw",
      county: "Cobb",
      pop: 56781,
    },
    {
      zip: "30145",
      city: "Kingston",
      county: "Bartow",
      pop: 7655,
    },
    {
      zip: "30147",
      city: "Lindale",
      county: "Floyd",
      pop: 5331,
    },
    {
      zip: "30148",
      city: "Marble Hill",
      county: "Pickens",
      pop: 762,
    },
    {
      zip: "30149",
      city: "Mount Berry",
      county: "Floyd",
      pop: 2004,
    },
    {
      zip: "30152",
      city: "Kennesaw",
      county: "Cobb",
      pop: 43030,
    },
    {
      zip: "30153",
      city: "Rockmart",
      county: "Polk",
      pop: 18688,
    },
    {
      zip: "30157",
      city: "Dallas",
      county: "Paulding",
      pop: 48978,
    },
    {
      zip: "30161",
      city: "Rome",
      county: "Floyd",
      pop: 34159,
    },
    {
      zip: "30164",
      city: "Rome",
      county: "Floyd",
      pop: 0,
    },
    {
      zip: "30165",
      city: "Rome",
      county: "Floyd",
      pop: 41536,
    },
    {
      zip: "30168",
      city: "Austell",
      county: "Cobb",
      pop: 25803,
    },
    {
      zip: "30170",
      city: "Roopville",
      county: "Carroll",
      pop: 2904,
    },
    {
      zip: "30171",
      city: "Rydal",
      county: "Bartow",
      pop: 3282,
    },
    {
      zip: "30173",
      city: "Silver Creek",
      county: "Floyd",
      pop: 5564,
    },
    {
      zip: "30175",
      city: "Talking Rock",
      county: "Pickens",
      pop: 5409,
    },
    {
      zip: "30176",
      city: "Tallapoosa",
      county: "Haralson",
      pop: 6838,
    },
    {
      zip: "30177",
      city: "Tate",
      county: "Pickens",
      pop: 1273,
    },
    {
      zip: "30178",
      city: "Taylorsville",
      county: "Bartow",
      pop: 3005,
    },
    {
      zip: "30179",
      city: "Temple",
      county: "Carroll",
      pop: 18176,
    },
    {
      zip: "30180",
      city: "Villa Rica",
      county: "Carroll",
      pop: 36888,
    },
    {
      zip: "30182",
      city: "Waco",
      county: "Haralson",
      pop: 2501,
    },
    {
      zip: "30183",
      city: "Waleska",
      county: "Cherokee",
      pop: 6365,
    },
    {
      zip: "30184",
      city: "White",
      county: "Bartow",
      pop: 6504,
    },
    {
      zip: "30185",
      city: "Whitesburg",
      county: "Carroll",
      pop: 4494,
    },
    {
      zip: "30187",
      city: "Winston",
      county: "Douglas",
      pop: 7798,
    },
    {
      zip: "30188",
      city: "Woodstock",
      county: "Cherokee",
      pop: 64836,
    },
    {
      zip: "30189",
      city: "Woodstock",
      county: "Cherokee",
      pop: 38809,
    },
    {
      zip: "30204",
      city: "Barnesville",
      county: "Lamar",
      pop: 13151,
    },
    {
      zip: "30205",
      city: "Brooks",
      county: "Fayette",
      pop: 2862,
    },
    {
      zip: "30206",
      city: "Concord",
      county: "Pike",
      pop: 3789,
    },
    {
      zip: "30213",
      city: "Fairburn",
      county: "Fulton",
      pop: 33926,
    },
    {
      zip: "30214",
      city: "Fayetteville",
      county: "Fayette",
      pop: 29577,
    },
    {
      zip: "30215",
      city: "Fayetteville",
      county: "Fayette",
      pop: 36879,
    },
    {
      zip: "30216",
      city: "Flovilla",
      county: "Butts",
      pop: 2361,
    },
    {
      zip: "30217",
      city: "Franklin",
      county: "Heard",
      pop: 9537,
    },
    {
      zip: "30218",
      city: "Gay",
      county: "Meriwether",
      pop: 1868,
    },
    {
      zip: "30220",
      city: "Grantville",
      county: "Coweta",
      pop: 5642,
    },
    {
      zip: "30222",
      city: "Greenville",
      county: "Meriwether",
      pop: 4089,
    },
    {
      zip: "30223",
      city: "Griffin",
      county: "Spalding",
      pop: 36501,
    },
    {
      zip: "30224",
      city: "Griffin",
      county: "Spalding",
      pop: 26453,
    },
    {
      zip: "30228",
      city: "Hampton",
      county: "Henry",
      pop: 44031,
    },
    {
      zip: "30230",
      city: "Hogansville",
      county: "Troup",
      pop: 9882,
    },
    {
      zip: "30233",
      city: "Jackson",
      county: "Butts",
      pop: 23821,
    },
    {
      zip: "30234",
      city: "Jenkinsburg",
      county: "Butts",
      pop: 1774,
    },
    {
      zip: "30236",
      city: "Jonesboro",
      county: "Clayton",
      pop: 51199,
    },
    {
      zip: "30238",
      city: "Jonesboro",
      county: "Clayton",
      pop: 39084,
    },
    {
      zip: "30240",
      city: "Lagrange",
      county: "Troup",
      pop: 29320,
    },
    {
      zip: "30241",
      city: "Lagrange",
      county: "Troup",
      pop: 25283,
    },
    {
      zip: "30248",
      city: "Locust Grove",
      county: "Henry",
      pop: 26317,
    },
    {
      zip: "30250",
      city: "Lovejoy",
      county: "Clayton",
      pop: 630,
    },
    {
      zip: "30251",
      city: "Luthersville",
      county: "Meriwether",
      pop: 2313,
    },
    {
      zip: "30252",
      city: "Mcdonough",
      county: "Henry",
      pop: 48203,
    },
    {
      zip: "30253",
      city: "Mcdonough",
      county: "Henry",
      pop: 53958,
    },
    {
      zip: "30256",
      city: "Meansville",
      county: "Pike",
      pop: 3007,
    },
    {
      zip: "30257",
      city: "Milner",
      county: "Lamar",
      pop: 4336,
    },
    {
      zip: "30258",
      city: "Molena",
      county: "Pike",
      pop: 3035,
    },
    {
      zip: "30259",
      city: "Moreland",
      county: "Coweta",
      pop: 3219,
    },
    {
      zip: "30260",
      city: "Morrow",
      county: "Clayton",
      pop: 25368,
    },
    {
      zip: "30263",
      city: "Newnan",
      county: "Coweta",
      pop: 59799,
    },
    {
      zip: "30265",
      city: "Newnan",
      county: "Coweta",
      pop: 35096,
    },
    {
      zip: "30268",
      city: "Palmetto",
      county: "Fulton",
      pop: 10298,
    },
    {
      zip: "30269",
      city: "Peachtree City",
      county: "Fayette",
      pop: 36489,
    },
    {
      zip: "30273",
      city: "Rex",
      county: "Clayton",
      pop: 15015,
    },
    {
      zip: "30274",
      city: "Riverdale",
      county: "Clayton",
      pop: 35861,
    },
    {
      zip: "30275",
      city: "Sargent",
      county: "Coweta",
      pop: 70,
    },
    {
      zip: "30276",
      city: "Senoia",
      county: "Coweta",
      pop: 16028,
    },
    {
      zip: "30277",
      city: "Sharpsburg",
      county: "Coweta",
      pop: 23058,
    },
    {
      zip: "30281",
      city: "Stockbridge",
      county: "Henry",
      pop: 68456,
    },
    {
      zip: "30284",
      city: "Sunny Side",
      county: "Spalding",
      pop: 103,
    },
    {
      zip: "30285",
      city: "The Rock",
      county: "Upson",
      pop: 730,
    },
    {
      zip: "30286",
      city: "Thomaston",
      county: "Upson",
      pop: 22143,
    },
    {
      zip: "30288",
      city: "Conley",
      county: "Dekalb",
      pop: 8749,
    },
    {
      zip: "30289",
      city: "Turin",
      county: "Coweta",
      pop: 52,
    },
    {
      zip: "30290",
      city: "Tyrone",
      county: "Fayette",
      pop: 8798,
    },
    {
      zip: "30291",
      city: "Union City",
      county: "Fulton",
      pop: 21639,
    },
    {
      zip: "30292",
      city: "Williamson",
      county: "Pike",
      pop: 5650,
    },
    {
      zip: "30293",
      city: "Woodbury",
      county: "Meriwether",
      pop: 2609,
    },
    {
      zip: "30294",
      city: "Ellenwood",
      county: "Clayton",
      pop: 42484,
    },
    {
      zip: "30295",
      city: "Zebulon",
      county: "Pike",
      pop: 4214,
    },
    {
      zip: "30296",
      city: "Riverdale",
      county: "Clayton",
      pop: 28169,
    },
    {
      zip: "30297",
      city: "Forest Park",
      county: "Clayton",
      pop: 28966,
    },
    {
      zip: "30303",
      city: "Atlanta",
      county: "Fulton",
      pop: 6628,
    },
    {
      zip: "30305",
      city: "Atlanta",
      county: "Fulton",
      pop: 24551,
    },
    {
      zip: "30306",
      city: "Atlanta",
      county: "Fulton",
      pop: 23973,
    },
    {
      zip: "30307",
      city: "Atlanta",
      county: "Fulton",
      pop: 20036,
    },
    {
      zip: "30308",
      city: "Atlanta",
      county: "Fulton",
      pop: 18839,
    },
    {
      zip: "30309",
      city: "Atlanta",
      county: "Fulton",
      pop: 26526,
    },
    {
      zip: "30310",
      city: "Atlanta",
      county: "Fulton",
      pop: 28664,
    },
    {
      zip: "30311",
      city: "Atlanta",
      county: "Fulton",
      pop: 36389,
    },
    {
      zip: "30312",
      city: "Atlanta",
      county: "Fulton",
      pop: 24782,
    },
    {
      zip: "30313",
      city: "Atlanta",
      county: "Fulton",
      pop: 11415,
    },
    {
      zip: "30314",
      city: "Atlanta",
      county: "Fulton",
      pop: 24974,
    },
    {
      zip: "30315",
      city: "Atlanta",
      county: "Fulton",
      pop: 35143,
    },
    {
      zip: "30316",
      city: "Atlanta",
      county: "Fulton",
      pop: 33670,
    },
    {
      zip: "30317",
      city: "Atlanta",
      county: "Fulton",
      pop: 13820,
    },
    {
      zip: "30318",
      city: "Atlanta",
      county: "Fulton",
      pop: 56109,
    },
    {
      zip: "30319",
      city: "Atlanta",
      county: "Dekalb",
      pop: 43011,
    },
    {
      zip: "30322",
      city: "Atlanta",
      county: "Dekalb",
      pop: 2780,
    },
    {
      zip: "30324",
      city: "Atlanta",
      county: "Fulton",
      pop: 27806,
    },
    {
      zip: "30326",
      city: "Atlanta",
      county: "Fulton",
      pop: 6529,
    },
    {
      zip: "30327",
      city: "Atlanta",
      county: "Fulton",
      pop: 22893,
    },
    {
      zip: "30328",
      city: "Atlanta",
      county: "Fulton",
      pop: 38648,
    },
    {
      zip: "30329",
      city: "Atlanta",
      county: "Dekalb",
      pop: 28383,
    },
    {
      zip: "30331",
      city: "Atlanta",
      county: "Fulton",
      pop: 66658,
    },
    {
      zip: "30332",
      city: "Atlanta",
      county: "Fulton",
      pop: 3034,
    },
    {
      zip: "30334",
      city: "Atlanta",
      county: "Fulton",
      pop: 0,
    },
    {
      zip: "30336",
      city: "Atlanta",
      county: "Fulton",
      pop: 274,
    },
    {
      zip: "30337",
      city: "Atlanta",
      county: "Fulton",
      pop: 13962,
    },
    {
      zip: "30338",
      city: "Atlanta",
      county: "Fulton",
      pop: 35903,
    },
    {
      zip: "30339",
      city: "Atlanta",
      county: "Fulton",
      pop: 23960,
    },
    {
      zip: "30340",
      city: "Atlanta",
      county: "Dekalb",
      pop: 27796,
    },
    {
      zip: "30341",
      city: "Atlanta",
      county: "Dekalb",
      pop: 32601,
    },
    {
      zip: "30342",
      city: "Atlanta",
      county: "Fulton",
      pop: 30873,
    },
    {
      zip: "30344",
      city: "Atlanta",
      county: "Fulton",
      pop: 32690,
    },
    {
      zip: "30345",
      city: "Atlanta",
      county: "Dekalb",
      pop: 25797,
    },
    {
      zip: "30346",
      city: "Atlanta",
      county: "Dekalb",
      pop: 4914,
    },
    {
      zip: "30349",
      city: "Atlanta",
      county: "Fulton",
      pop: 74590,
    },
    {
      zip: "30350",
      city: "Atlanta",
      county: "Dekalb",
      pop: 39075,
    },
    {
      zip: "30354",
      city: "Atlanta",
      county: "Fulton",
      pop: 15680,
    },
    {
      zip: "30360",
      city: "Atlanta",
      county: "Dekalb",
      pop: 15856,
    },
    {
      zip: "30401",
      city: "Swainsboro",
      county: "Emanuel",
      pop: 13740,
    },
    {
      zip: "30410",
      city: "Ailey",
      county: "Montgomery",
      pop: 1813,
    },
    {
      zip: "30411",
      city: "Alamo",
      county: "Wheeler",
      pop: 5333,
    },
    {
      zip: "30412",
      city: "Alston",
      county: "Montgomery",
      pop: 65,
    },
    {
      zip: "30413",
      city: "Bartow",
      county: "Jefferson",
      pop: 1818,
    },
    {
      zip: "30415",
      city: "Brooklet",
      county: "Bulloch",
      pop: 6765,
    },
    {
      zip: "30417",
      city: "Claxton",
      county: "Evans",
      pop: 10768,
    },
    {
      zip: "30420",
      city: "Cobbtown",
      county: "Tattnall",
      pop: 988,
    },
    {
      zip: "30421",
      city: "Collins",
      county: "Tattnall",
      pop: 2723,
    },
    {
      zip: "30423",
      city: "Daisy",
      county: "Evans",
      pop: 222,
    },
    {
      zip: "30425",
      city: "Garfield",
      county: "Emanuel",
      pop: 1458,
    },
    {
      zip: "30426",
      city: "Girard",
      county: "Burke",
      pop: 773,
    },
    {
      zip: "30427",
      city: "Glennville",
      county: "Tattnall",
      pop: 12571,
    },
    {
      zip: "30428",
      city: "Glenwood",
      county: "Wheeler",
      pop: 2815,
    },
    {
      zip: "30429",
      city: "Hagan",
      county: "Evans",
      pop: 168,
    },
    {
      zip: "30434",
      city: "Louisville",
      county: "Jefferson",
      pop: 5331,
    },
    {
      zip: "30436",
      city: "Lyons",
      county: "Toombs",
      pop: 11879,
    },
    {
      zip: "30438",
      city: "Manassas",
      county: "Tattnall",
      pop: 24,
    },
    {
      zip: "30439",
      city: "Metter",
      county: "Candler",
      pop: 10819,
    },
    {
      zip: "30441",
      city: "Midville",
      county: "Burke",
      pop: 1689,
    },
    {
      zip: "30442",
      city: "Millen",
      county: "Jenkins",
      pop: 7887,
    },
    {
      zip: "30445",
      city: "Mount Vernon",
      county: "Montgomery",
      pop: 3851,
    },
    {
      zip: "30446",
      city: "Newington",
      county: "Screven",
      pop: 1055,
    },
    {
      zip: "30448",
      city: "Nunez",
      county: "Emanuel",
      pop: 80,
    },
    {
      zip: "30449",
      city: "Oliver",
      county: "Screven",
      pop: 140,
    },
    {
      zip: "30450",
      city: "Portal",
      county: "Bulloch",
      pop: 2170,
    },
    {
      zip: "30451",
      city: "Pulaski",
      county: "Candler",
      pop: 42,
    },
    {
      zip: "30452",
      city: "Register",
      county: "Bulloch",
      pop: 1576,
    },
    {
      zip: "30453",
      city: "Reidsville",
      county: "Tattnall",
      pop: 10936,
    },
    {
      zip: "30454",
      city: "Rockledge",
      county: "Laurens",
      pop: 866,
    },
    {
      zip: "30455",
      city: "Rocky Ford",
      county: "Screven",
      pop: 544,
    },
    {
      zip: "30456",
      city: "Sardis",
      county: "Burke",
      pop: 2099,
    },
    {
      zip: "30457",
      city: "Soperton",
      county: "Treutlen",
      pop: 5816,
    },
    {
      zip: "30458",
      city: "Statesboro",
      county: "Bulloch",
      pop: 44329,
    },
    {
      zip: "30460",
      city: "Statesboro",
      county: "Bulloch",
      pop: 2119,
    },
    {
      zip: "30461",
      city: "Statesboro",
      county: "Bulloch",
      pop: 13882,
    },
    {
      zip: "30464",
      city: "Stillmore",
      county: "Emanuel",
      pop: 122,
    },
    {
      zip: "30467",
      city: "Sylvania",
      county: "Screven",
      pop: 12184,
    },
    {
      zip: "30470",
      city: "Tarrytown",
      county: "Montgomery",
      pop: 337,
    },
    {
      zip: "30471",
      city: "Twin City",
      county: "Emanuel",
      pop: 4744,
    },
    {
      zip: "30473",
      city: "Uvalda",
      county: "Montgomery",
      pop: 2442,
    },
    {
      zip: "30474",
      city: "Vidalia",
      county: "Toombs",
      pop: 16913,
    },
    {
      zip: "30475",
      city: "Vidalia",
      county: "Toombs",
      pop: 0,
    },
    {
      zip: "30477",
      city: "Wadley",
      county: "Jefferson",
      pop: 2805,
    },
    {
      zip: "30501",
      city: "Gainesville",
      county: "Hall",
      pop: 31127,
    },
    {
      zip: "30504",
      city: "Gainesville",
      county: "Hall",
      pop: 27202,
    },
    {
      zip: "30506",
      city: "Gainesville",
      county: "Hall",
      pop: 43765,
    },
    {
      zip: "30507",
      city: "Gainesville",
      county: "Hall",
      pop: 30499,
    },
    {
      zip: "30510",
      city: "Alto",
      county: "Habersham",
      pop: 8488,
    },
    {
      zip: "30511",
      city: "Baldwin",
      county: "Banks",
      pop: 3874,
    },
    {
      zip: "30512",
      city: "Blairsville",
      county: "Union",
      pop: 21541,
    },
    {
      zip: "30513",
      city: "Blue Ridge",
      county: "Fannin",
      pop: 12108,
    },
    {
      zip: "30516",
      city: "Bowersville",
      county: "Hart",
      pop: 2221,
    },
    {
      zip: "30517",
      city: "Braselton",
      county: "Jackson",
      pop: 15909,
    },
    {
      zip: "30518",
      city: "Buford",
      county: "Gwinnett",
      pop: 53780,
    },
    {
      zip: "30519",
      city: "Buford",
      county: "Gwinnett",
      pop: 47685,
    },
    {
      zip: "30520",
      city: "Canon",
      county: "Franklin",
      pop: 5774,
    },
    {
      zip: "30521",
      city: "Carnesville",
      county: "Franklin",
      pop: 5018,
    },
    {
      zip: "30522",
      city: "Cherrylog",
      county: "Gilmer",
      pop: 987,
    },
    {
      zip: "30523",
      city: "Clarkesville",
      county: "Habersham",
      pop: 12465,
    },
    {
      zip: "30525",
      city: "Clayton",
      county: "Rabun",
      pop: 7730,
    },
    {
      zip: "30527",
      city: "Clermont",
      county: "Hall",
      pop: 4321,
    },
    {
      zip: "30528",
      city: "Cleveland",
      county: "White",
      pop: 25280,
    },
    {
      zip: "30529",
      city: "Commerce",
      county: "Jackson",
      pop: 11358,
    },
    {
      zip: "30530",
      city: "Commerce",
      county: "Jackson",
      pop: 6887,
    },
    {
      zip: "30531",
      city: "Cornelia",
      county: "Habersham",
      pop: 10924,
    },
    {
      zip: "30533",
      city: "Dahlonega",
      county: "Lumpkin",
      pop: 27113,
    },
    {
      zip: "30534",
      city: "Dawsonville",
      county: "Dawson",
      pop: 29530,
    },
    {
      zip: "30535",
      city: "Demorest",
      county: "Habersham",
      pop: 7984,
    },
    {
      zip: "30537",
      city: "Dillard",
      county: "Rabun",
      pop: 1552,
    },
    {
      zip: "30538",
      city: "Eastanollee",
      county: "Stephens",
      pop: 3404,
    },
    {
      zip: "30540",
      city: "Ellijay",
      county: "Gilmer",
      pop: 19634,
    },
    {
      zip: "30541",
      city: "Epworth",
      county: "Fannin",
      pop: 1498,
    },
    {
      zip: "30542",
      city: "Flowery Branch",
      county: "Hall",
      pop: 37185,
    },
    {
      zip: "30543",
      city: "Gillsville",
      county: "Hall",
      pop: 4570,
    },
    {
      zip: "30545",
      city: "Helen",
      county: "White",
      pop: 929,
    },
    {
      zip: "30546",
      city: "Hiawassee",
      county: "Towns",
      pop: 7199,
    },
    {
      zip: "30547",
      city: "Homer",
      county: "Banks",
      pop: 3057,
    },
    {
      zip: "30548",
      city: "Hoschton",
      county: "Jackson",
      pop: 19796,
    },
    {
      zip: "30549",
      city: "Jefferson",
      county: "Jackson",
      pop: 25530,
    },
    {
      zip: "30552",
      city: "Lakemont",
      county: "Rabun",
      pop: 1741,
    },
    {
      zip: "30553",
      city: "Lavonia",
      county: "Franklin",
      pop: 8009,
    },
    {
      zip: "30554",
      city: "Lula",
      county: "Hall",
      pop: 8126,
    },
    {
      zip: "30555",
      city: "Mc Caysville",
      county: "Fannin",
      pop: 2400,
    },
    {
      zip: "30557",
      city: "Martin",
      county: "Stephens",
      pop: 5076,
    },
    {
      zip: "30558",
      city: "Maysville",
      county: "Banks",
      pop: 5322,
    },
    {
      zip: "30559",
      city: "Mineral Bluff",
      county: "Fannin",
      pop: 4740,
    },
    {
      zip: "30560",
      city: "Morganton",
      county: "Fannin",
      pop: 4772,
    },
    {
      zip: "30562",
      city: "Mountain City",
      county: "Rabun",
      pop: 1326,
    },
    {
      zip: "30563",
      city: "Mount Airy",
      county: "Habersham",
      pop: 5973,
    },
    {
      zip: "30564",
      city: "Murrayville",
      county: "Hall",
      pop: 3844,
    },
    {
      zip: "30565",
      city: "Nicholson",
      county: "Jackson",
      pop: 4614,
    },
    {
      zip: "30566",
      city: "Oakwood",
      county: "Hall",
      pop: 7710,
    },
    {
      zip: "30567",
      city: "Pendergrass",
      county: "Jackson",
      pop: 3820,
    },
    {
      zip: "30568",
      city: "Rabun Gap",
      county: "Rabun",
      pop: 1348,
    },
    {
      zip: "30571",
      city: "Sautee Nacoochee",
      county: "White",
      pop: 3459,
    },
    {
      zip: "30572",
      city: "Suches",
      county: "Union",
      pop: 864,
    },
    {
      zip: "30573",
      city: "Tallulah Falls",
      county: "Rabun",
      pop: 46,
    },
    {
      zip: "30575",
      city: "Talmo",
      county: "Jackson",
      pop: 1800,
    },
    {
      zip: "30576",
      city: "Tiger",
      county: "Rabun",
      pop: 2574,
    },
    {
      zip: "30577",
      city: "Toccoa",
      county: "Stephens",
      pop: 20814,
    },
    {
      zip: "30581",
      city: "Wiley",
      county: "Rabun",
      pop: 141,
    },
    {
      zip: "30582",
      city: "Young Harris",
      county: "Towns",
      pop: 4998,
    },
    {
      zip: "30601",
      city: "Athens",
      county: "Clarke",
      pop: 24267,
    },
    {
      zip: "30602",
      city: "Athens",
      county: "Clarke",
      pop: 2952,
    },
    {
      zip: "30605",
      city: "Athens",
      county: "Clarke",
      pop: 41593,
    },
    {
      zip: "30606",
      city: "Athens",
      county: "Clarke",
      pop: 45457,
    },
    {
      zip: "30607",
      city: "Athens",
      county: "Clarke",
      pop: 10474,
    },
    {
      zip: "30609",
      city: "Athens",
      county: "Clarke",
      pop: 2308,
    },
    {
      zip: "30619",
      city: "Arnoldsville",
      county: "Oglethorpe",
      pop: 1141,
    },
    {
      zip: "30620",
      city: "Bethlehem",
      county: "Barrow",
      pop: 14228,
    },
    {
      zip: "30621",
      city: "Bishop",
      county: "Oconee",
      pop: 5300,
    },
    {
      zip: "30622",
      city: "Bogart",
      county: "Oconee",
      pop: 11846,
    },
    {
      zip: "30623",
      city: "Bostwick",
      county: "Morgan",
      pop: 67,
    },
    {
      zip: "30624",
      city: "Bowman",
      county: "Elbert",
      pop: 3273,
    },
    {
      zip: "30625",
      city: "Buckhead",
      county: "Morgan",
      pop: 2327,
    },
    {
      zip: "30627",
      city: "Carlton",
      county: "Madison",
      pop: 2418,
    },
    {
      zip: "30628",
      city: "Colbert",
      county: "Madison",
      pop: 7391,
    },
    {
      zip: "30629",
      city: "Comer",
      county: "Madison",
      pop: 4832,
    },
    {
      zip: "30630",
      city: "Crawford",
      county: "Oglethorpe",
      pop: 2285,
    },
    {
      zip: "30631",
      city: "Crawfordville",
      county: "Taliaferro",
      pop: 1623,
    },
    {
      zip: "30633",
      city: "Danielsville",
      county: "Madison",
      pop: 8979,
    },
    {
      zip: "30634",
      city: "Dewy Rose",
      county: "Elbert",
      pop: 1949,
    },
    {
      zip: "30635",
      city: "Elberton",
      county: "Elbert",
      pop: 14996,
    },
    {
      zip: "30641",
      city: "Good Hope",
      county: "Walton",
      pop: 1882,
    },
    {
      zip: "30642",
      city: "Greensboro",
      county: "Greene",
      pop: 12392,
    },
    {
      zip: "30643",
      city: "Hartwell",
      county: "Hart",
      pop: 15166,
    },
    {
      zip: "30646",
      city: "Hull",
      county: "Madison",
      pop: 6945,
    },
    {
      zip: "30648",
      city: "Lexington",
      county: "Oglethorpe",
      pop: 3003,
    },
    {
      zip: "30650",
      city: "Madison",
      county: "Morgan",
      pop: 12020,
    },
    {
      zip: "30655",
      city: "Monroe",
      county: "Walton",
      pop: 26516,
    },
    {
      zip: "30656",
      city: "Monroe",
      county: "Walton",
      pop: 15284,
    },
    {
      zip: "30660",
      city: "Rayle",
      county: "Wilkes",
      pop: 1270,
    },
    {
      zip: "30662",
      city: "Royston",
      county: "Franklin",
      pop: 8941,
    },
    {
      zip: "30663",
      city: "Rutledge",
      county: "Morgan",
      pop: 3255,
    },
    {
      zip: "30664",
      city: "Sharon",
      county: "Taliaferro",
      pop: 19,
    },
    {
      zip: "30665",
      city: "Siloam",
      county: "Greene",
      pop: 77,
    },
    {
      zip: "30666",
      city: "Statham",
      county: "Barrow",
      pop: 10876,
    },
    {
      zip: "30667",
      city: "Stephens",
      county: "Oglethorpe",
      pop: 855,
    },
    {
      zip: "30668",
      city: "Tignall",
      county: "Wilkes",
      pop: 1650,
    },
    {
      zip: "30669",
      city: "Union Point",
      county: "Greene",
      pop: 3263,
    },
    {
      zip: "30673",
      city: "Washington",
      county: "Wilkes",
      pop: 7180,
    },
    {
      zip: "30677",
      city: "Watkinsville",
      county: "Oconee",
      pop: 18450,
    },
    {
      zip: "30678",
      city: "White Plains",
      county: "Greene",
      pop: 1383,
    },
    {
      zip: "30680",
      city: "Winder",
      county: "Barrow",
      pop: 44800,
    },
    {
      zip: "30683",
      city: "Winterville",
      county: "Clarke",
      pop: 6866,
    },
    {
      zip: "30701",
      city: "Calhoun",
      county: "Gordon",
      pop: 40974,
    },
    {
      zip: "30705",
      city: "Chatsworth",
      county: "Murray",
      pop: 34031,
    },
    {
      zip: "30707",
      city: "Chickamauga",
      county: "Walker",
      pop: 16593,
    },
    {
      zip: "30708",
      city: "Cisco",
      county: "Murray",
      pop: 241,
    },
    {
      zip: "30710",
      city: "Cohutta",
      county: "Whitfield",
      pop: 7158,
    },
    {
      zip: "30711",
      city: "Crandall",
      county: "Murray",
      pop: 3332,
    },
    {
      zip: "30720",
      city: "Dalton",
      county: "Whitfield",
      pop: 27414,
    },
    {
      zip: "30721",
      city: "Dalton",
      county: "Whitfield",
      pop: 53960,
    },
    {
      zip: "30725",
      city: "Flintstone",
      county: "Walker",
      pop: 4442,
    },
    {
      zip: "30726",
      city: "Graysville",
      county: "Catoosa",
      pop: 0,
    },
    {
      zip: "30728",
      city: "La Fayette",
      county: "Walker",
      pop: 20426,
    },
    {
      zip: "30730",
      city: "Lyerly",
      county: "Chattooga",
      pop: 1711,
    },
    {
      zip: "30731",
      city: "Menlo",
      county: "Chattooga",
      pop: 2314,
    },
    {
      zip: "30733",
      city: "Plainville",
      county: "Gordon",
      pop: 2027,
    },
    {
      zip: "30734",
      city: "Ranger",
      county: "Gordon",
      pop: 3608,
    },
    {
      zip: "30735",
      city: "Resaca",
      county: "Gordon",
      pop: 6719,
    },
    {
      zip: "30736",
      city: "Ringgold",
      county: "Catoosa",
      pop: 42604,
    },
    {
      zip: "30738",
      city: "Rising Fawn",
      county: "Dade",
      pop: 3697,
    },
    {
      zip: "30739",
      city: "Rock Spring",
      county: "Walker",
      pop: 7237,
    },
    {
      zip: "30740",
      city: "Rocky Face",
      county: "Whitfield",
      pop: 8428,
    },
    {
      zip: "30741",
      city: "Rossville",
      county: "Walker",
      pop: 28520,
    },
    {
      zip: "30742",
      city: "Fort Oglethorpe",
      county: "Catoosa",
      pop: 7882,
    },
    {
      zip: "30746",
      city: "Sugar Valley",
      county: "Gordon",
      pop: 1025,
    },
    {
      zip: "30747",
      city: "Summerville",
      county: "Chattooga",
      pop: 15902,
    },
    {
      zip: "30750",
      city: "Lookout Mountain",
      county: "Walker",
      pop: 4558,
    },
    {
      zip: "30751",
      city: "Tennga",
      county: "Murray",
      pop: 46,
    },
    {
      zip: "30752",
      city: "Trenton",
      county: "Dade",
      pop: 8616,
    },
    {
      zip: "30753",
      city: "Trion",
      county: "Chattooga",
      pop: 6873,
    },
    {
      zip: "30755",
      city: "Tunnel Hill",
      county: "Whitfield",
      pop: 9784,
    },
    {
      zip: "30756",
      city: "Varnell",
      county: "Whitfield",
      pop: 143,
    },
    {
      zip: "30757",
      city: "Wildwood",
      county: "Dade",
      pop: 2061,
    },
    {
      zip: "30802",
      city: "Appling",
      county: "Columbia",
      pop: 6173,
    },
    {
      zip: "30803",
      city: "Avera",
      county: "Jefferson",
      pop: 988,
    },
    {
      zip: "30805",
      city: "Blythe",
      county: "Richmond",
      pop: 2408,
    },
    {
      zip: "30807",
      city: "Camak",
      county: "Warren",
      pop: 83,
    },
    {
      zip: "30808",
      city: "Dearing",
      county: "Mcduffie",
      pop: 4157,
    },
    {
      zip: "30809",
      city: "Evans",
      county: "Columbia",
      pop: 48525,
    },
    {
      zip: "30810",
      city: "Gibson",
      county: "Glascock",
      pop: 2049,
    },
    {
      zip: "30812",
      city: "Gracewood",
      county: "Richmond",
      pop: 413,
    },
    {
      zip: "30813",
      city: "Grovetown",
      county: "Columbia",
      pop: 44459,
    },
    {
      zip: "30814",
      city: "Harlem",
      county: "Columbia",
      pop: 8673,
    },
    {
      zip: "30815",
      city: "Hephzibah",
      county: "Richmond",
      pop: 41629,
    },
    {
      zip: "30816",
      city: "Keysville",
      county: "Burke",
      pop: 1895,
    },
    {
      zip: "30817",
      city: "Lincolnton",
      county: "Lincoln",
      pop: 7747,
    },
    {
      zip: "30818",
      city: "Matthews",
      county: "Jefferson",
      pop: 648,
    },
    {
      zip: "30820",
      city: "Mitchell",
      county: "Glascock",
      pop: 1032,
    },
    {
      zip: "30821",
      city: "Norwood",
      county: "Warren",
      pop: 884,
    },
    {
      zip: "30822",
      city: "Perkins",
      county: "Jenkins",
      pop: 600,
    },
    {
      zip: "30823",
      city: "Stapleton",
      county: "Jefferson",
      pop: 1469,
    },
    {
      zip: "30824",
      city: "Thomson",
      county: "Mcduffie",
      pop: 17266,
    },
    {
      zip: "30828",
      city: "Warrenton",
      county: "Warren",
      pop: 4052,
    },
    {
      zip: "30830",
      city: "Waynesboro",
      county: "Burke",
      pop: 13927,
    },
    {
      zip: "30833",
      city: "Wrens",
      county: "Jefferson",
      pop: 3589,
    },
    {
      zip: "30901",
      city: "Augusta",
      county: "Richmond",
      pop: 16338,
    },
    {
      zip: "30903",
      city: "Augusta",
      county: "Richmond",
      pop: 791,
    },
    {
      zip: "30904",
      city: "Augusta",
      county: "Richmond",
      pop: 25175,
    },
    {
      zip: "30905",
      city: "Augusta",
      county: "Richmond",
      pop: 7869,
    },
    {
      zip: "30906",
      city: "Augusta",
      county: "Richmond",
      pop: 59609,
    },
    {
      zip: "30907",
      city: "Augusta",
      county: "Richmond",
      pop: 52252,
    },
    {
      zip: "30909",
      city: "Augusta",
      county: "Richmond",
      pop: 41261,
    },
    {
      zip: "30912",
      city: "Augusta",
      county: "Richmond",
      pop: 183,
    },
    {
      zip: "31001",
      city: "Abbeville",
      county: "Wilcox",
      pop: 4547,
    },
    {
      zip: "31002",
      city: "Adrian",
      county: "Emanuel",
      pop: 3065,
    },
    {
      zip: "31003",
      city: "Allentown",
      county: "Wilkinson",
      pop: 87,
    },
    {
      zip: "31005",
      city: "Bonaire",
      county: "Houston",
      pop: 17961,
    },
    {
      zip: "31006",
      city: "Butler",
      county: "Taylor",
      pop: 4411,
    },
    {
      zip: "31007",
      city: "Byromville",
      county: "Dooly",
      pop: 1070,
    },
    {
      zip: "31008",
      city: "Byron",
      county: "Peach",
      pop: 18046,
    },
    {
      zip: "31009",
      city: "Cadwell",
      county: "Laurens",
      pop: 1260,
    },
    {
      zip: "31011",
      city: "Chauncey",
      county: "Dodge",
      pop: 902,
    },
    {
      zip: "31012",
      city: "Chester",
      county: "Dodge",
      pop: 2963,
    },
    {
      zip: "31014",
      city: "Cochran",
      county: "Bleckley",
      pop: 13180,
    },
    {
      zip: "31015",
      city: "Cordele",
      county: "Crisp",
      pop: 21466,
    },
    {
      zip: "31016",
      city: "Culloden",
      county: "Monroe",
      pop: 2167,
    },
    {
      zip: "31017",
      city: "Danville",
      county: "Twiggs",
      pop: 1984,
    },
    {
      zip: "31018",
      city: "Davisboro",
      county: "Washington",
      pop: 2673,
    },
    {
      zip: "31019",
      city: "Dexter",
      county: "Laurens",
      pop: 2156,
    },
    {
      zip: "31020",
      city: "Dry Branch",
      county: "Twiggs",
      pop: 1580,
    },
    {
      zip: "31021",
      city: "Dublin",
      county: "Laurens",
      pop: 27976,
    },
    {
      zip: "31022",
      city: "Dudley",
      county: "Laurens",
      pop: 1801,
    },
    {
      zip: "31023",
      city: "Eastman",
      county: "Dodge",
      pop: 14315,
    },
    {
      zip: "31024",
      city: "Eatonton",
      county: "Putnam",
      pop: 20626,
    },
    {
      zip: "31025",
      city: "Elko",
      county: "Houston",
      pop: 879,
    },
    {
      zip: "31027",
      city: "Dublin",
      county: "Laurens",
      pop: 8803,
    },
    {
      zip: "31028",
      city: "Centerville",
      county: "Houston",
      pop: 6406,
    },
    {
      zip: "31029",
      city: "Forsyth",
      county: "Monroe",
      pop: 16322,
    },
    {
      zip: "31030",
      city: "Fort Valley",
      county: "Peach",
      pop: 17926,
    },
    {
      zip: "31031",
      city: "Gordon",
      county: "Wilkinson",
      pop: 6780,
    },
    {
      zip: "31032",
      city: "Gray",
      county: "Jones",
      pop: 15580,
    },
    {
      zip: "31033",
      city: "Haddock",
      county: "Jones",
      pop: 1937,
    },
    {
      zip: "31035",
      city: "Harrison",
      county: "Washington",
      pop: 1098,
    },
    {
      zip: "31036",
      city: "Hawkinsville",
      county: "Pulaski",
      pop: 12077,
    },
    {
      zip: "31037",
      city: "Helena",
      county: "Telfair",
      pop: 3838,
    },
    {
      zip: "31038",
      city: "Hillsboro",
      county: "Jasper",
      pop: 458,
    },
    {
      zip: "31039",
      city: "Howard",
      county: "Taylor",
      pop: 0,
    },
    {
      zip: "31041",
      city: "Ideal",
      county: "Macon",
      pop: 623,
    },
    {
      zip: "31042",
      city: "Irwinton",
      county: "Wilkinson",
      pop: 1429,
    },
    {
      zip: "31044",
      city: "Jeffersonville",
      county: "Twiggs",
      pop: 3161,
    },
    {
      zip: "31045",
      city: "Jewell",
      county: "Warren",
      pop: 13,
    },
    {
      zip: "31046",
      city: "Juliette",
      county: "Monroe",
      pop: 3348,
    },
    {
      zip: "31047",
      city: "Kathleen",
      county: "Houston",
      pop: 14908,
    },
    {
      zip: "31049",
      city: "Kite",
      county: "Johnson",
      pop: 1961,
    },
    {
      zip: "31050",
      city: "Knoxville",
      county: "Crawford",
      pop: 843,
    },
    {
      zip: "31051",
      city: "Lilly",
      county: "Dooly",
      pop: 156,
    },
    {
      zip: "31052",
      city: "Lizella",
      county: "Crawford",
      pop: 9028,
    },
    {
      zip: "31054",
      city: "Mc Intyre",
      county: "Wilkinson",
      pop: 1505,
    },
    {
      zip: "31055",
      city: "Mc Rae",
      county: "Telfair",
      pop: 8565,
    },
    {
      zip: "31057",
      city: "Marshallville",
      county: "Macon",
      pop: 2006,
    },
    {
      zip: "31058",
      city: "Mauk",
      county: "Taylor",
      pop: 1827,
    },
    {
      zip: "31060",
      city: "Milan",
      county: "Telfair",
      pop: 1642,
    },
    {
      zip: "31061",
      city: "Milledgeville",
      county: "Baldwin",
      pop: 43123,
    },
    {
      zip: "31062",
      city: "Milledgeville",
      county: "Baldwin",
      pop: 477,
    },
    {
      zip: "31063",
      city: "Montezuma",
      county: "Macon",
      pop: 5006,
    },
    {
      zip: "31064",
      city: "Monticello",
      county: "Jasper",
      pop: 9478,
    },
    {
      zip: "31065",
      city: "Montrose",
      county: "Laurens",
      pop: 1169,
    },
    {
      zip: "31066",
      city: "Musella",
      county: "Crawford",
      pop: 1291,
    },
    {
      zip: "31067",
      city: "Oconee",
      county: "Washington",
      pop: 288,
    },
    {
      zip: "31068",
      city: "Oglethorpe",
      county: "Macon",
      pop: 5329,
    },
    {
      zip: "31069",
      city: "Perry",
      county: "Houston",
      pop: 20296,
    },
    {
      zip: "31070",
      city: "Pinehurst",
      county: "Dooly",
      pop: 1179,
    },
    {
      zip: "31071",
      city: "Pineview",
      county: "Wilcox",
      pop: 1297,
    },
    {
      zip: "31072",
      city: "Pitts",
      county: "Wilcox",
      pop: 1278,
    },
    {
      zip: "31075",
      city: "Rentz",
      county: "Laurens",
      pop: 2978,
    },
    {
      zip: "31076",
      city: "Reynolds",
      county: "Taylor",
      pop: 3124,
    },
    {
      zip: "31077",
      city: "Rhine",
      county: "Dodge",
      pop: 1363,
    },
    {
      zip: "31078",
      city: "Roberta",
      county: "Crawford",
      pop: 2861,
    },
    {
      zip: "31079",
      city: "Rochelle",
      county: "Wilcox",
      pop: 2212,
    },
    {
      zip: "31081",
      city: "Rupert",
      county: "Taylor",
      pop: 16,
    },
    {
      zip: "31082",
      city: "Sandersville",
      county: "Washington",
      pop: 9728,
    },
    {
      zip: "31083",
      city: "Scotland",
      county: "Telfair",
      pop: 386,
    },
    {
      zip: "31084",
      city: "Seville",
      county: "Wilcox",
      pop: 65,
    },
    {
      zip: "31085",
      city: "Shady Dale",
      county: "Jasper",
      pop: 1116,
    },
    {
      zip: "31087",
      city: "Sparta",
      county: "Hancock",
      pop: 8659,
    },
    {
      zip: "31088",
      city: "Warner Robins",
      county: "Houston",
      pop: 57094,
    },
    {
      zip: "31089",
      city: "Tennille",
      county: "Washington",
      pop: 4427,
    },
    {
      zip: "31090",
      city: "Toomsboro",
      county: "Wilkinson",
      pop: 1072,
    },
    {
      zip: "31091",
      city: "Unadilla",
      county: "Dooly",
      pop: 4376,
    },
    {
      zip: "31092",
      city: "Vienna",
      county: "Dooly",
      pop: 6843,
    },
    {
      zip: "31093",
      city: "Warner Robins",
      county: "Houston",
      pop: 27313,
    },
    {
      zip: "31094",
      city: "Warthen",
      county: "Washington",
      pop: 1116,
    },
    {
      zip: "31096",
      city: "Wrightsville",
      county: "Johnson",
      pop: 7039,
    },
    {
      zip: "31097",
      city: "Yatesville",
      county: "Upson",
      pop: 1345,
    },
    {
      zip: "31098",
      city: "Warner Robins",
      county: "Houston",
      pop: 3489,
    },
    {
      zip: "31201",
      city: "Macon",
      county: "Bibb",
      pop: 8391,
    },
    {
      zip: "31204",
      city: "Macon",
      county: "Bibb",
      pop: 29765,
    },
    {
      zip: "31206",
      city: "Macon",
      county: "Bibb",
      pop: 26216,
    },
    {
      zip: "31207",
      city: "Macon",
      county: "Bibb",
      pop: 1089,
    },
    {
      zip: "31210",
      city: "Macon",
      county: "Bibb",
      pop: 34230,
    },
    {
      zip: "31211",
      city: "Macon",
      county: "Bibb",
      pop: 15261,
    },
    {
      zip: "31213",
      city: "Macon",
      county: "Bibb",
      pop: 0,
    },
    {
      zip: "31216",
      city: "Macon",
      county: "Bibb",
      pop: 16802,
    },
    {
      zip: "31217",
      city: "Macon",
      county: "Bibb",
      pop: 16484,
    },
    {
      zip: "31220",
      city: "Macon",
      county: "Bibb",
      pop: 14859,
    },
    {
      zip: "31301",
      city: "Allenhurst",
      county: "Liberty",
      pop: 3447,
    },
    {
      zip: "31302",
      city: "Bloomingdale",
      county: "Chatham",
      pop: 7794,
    },
    {
      zip: "31303",
      city: "Clyo",
      county: "Effingham",
      pop: 2682,
    },
    {
      zip: "31304",
      city: "Crescent",
      county: "Mcintosh",
      pop: 35,
    },
    {
      zip: "31305",
      city: "Darien",
      county: "Mcintosh",
      pop: 5409,
    },
    {
      zip: "31307",
      city: "Eden",
      county: "Effingham",
      pop: 947,
    },
    {
      zip: "31308",
      city: "Ellabell",
      county: "Bryan",
      pop: 7250,
    },
    {
      zip: "31309",
      city: "Fleming",
      county: "Liberty",
      pop: 923,
    },
    {
      zip: "31312",
      city: "Guyton",
      county: "Effingham",
      pop: 20873,
    },
    {
      zip: "31313",
      city: "Hinesville",
      county: "Liberty",
      pop: 40467,
    },
    {
      zip: "31314",
      city: "Fort Stewart",
      county: "Liberty",
      pop: 1621,
    },
    {
      zip: "31315",
      city: "Fort Stewart",
      county: "Liberty",
      pop: 8022,
    },
    {
      zip: "31316",
      city: "Ludowici",
      county: "Long",
      pop: 14117,
    },
    {
      zip: "31318",
      city: "Meldrim",
      county: "Effingham",
      pop: 387,
    },
    {
      zip: "31320",
      city: "Midway",
      county: "Liberty",
      pop: 7769,
    },
    {
      zip: "31321",
      city: "Pembroke",
      county: "Bryan",
      pop: 7947,
    },
    {
      zip: "31322",
      city: "Pooler",
      county: "Chatham",
      pop: 26126,
    },
    {
      zip: "31323",
      city: "Riceboro",
      county: "Liberty",
      pop: 1257,
    },
    {
      zip: "31324",
      city: "Richmond Hill",
      county: "Bryan",
      pop: 26684,
    },
    {
      zip: "31326",
      city: "Rincon",
      county: "Effingham",
      pop: 20933,
    },
    {
      zip: "31327",
      city: "Sapelo Island",
      county: "Mcintosh",
      pop: 212,
    },
    {
      zip: "31328",
      city: "Tybee Island",
      county: "Chatham",
      pop: 3460,
    },
    {
      zip: "31329",
      city: "Springfield",
      county: "Effingham",
      pop: 10499,
    },
    {
      zip: "31331",
      city: "Townsend",
      county: "Mcintosh",
      pop: 8475,
    },
    {
      zip: "31401",
      city: "Savannah",
      county: "Chatham",
      pop: 19839,
    },
    {
      zip: "31404",
      city: "Savannah",
      county: "Chatham",
      pop: 32816,
    },
    {
      zip: "31405",
      city: "Savannah",
      county: "Chatham",
      pop: 37399,
    },
    {
      zip: "31406",
      city: "Savannah",
      county: "Chatham",
      pop: 35227,
    },
    {
      zip: "31407",
      city: "Savannah",
      county: "Chatham",
      pop: 13879,
    },
    {
      zip: "31408",
      city: "Savannah",
      county: "Chatham",
      pop: 10371,
    },
    {
      zip: "31409",
      city: "Savannah",
      county: "Chatham",
      pop: 885,
    },
    {
      zip: "31410",
      city: "Savannah",
      county: "Chatham",
      pop: 24727,
    },
    {
      zip: "31411",
      city: "Savannah",
      county: "Chatham",
      pop: 9076,
    },
    {
      zip: "31415",
      city: "Savannah",
      county: "Chatham",
      pop: 12209,
    },
    {
      zip: "31419",
      city: "Savannah",
      county: "Chatham",
      pop: 58800,
    },
    {
      zip: "31501",
      city: "Waycross",
      county: "Ware",
      pop: 15441,
    },
    {
      zip: "31503",
      city: "Waycross",
      county: "Ware",
      pop: 20344,
    },
    {
      zip: "31510",
      city: "Alma",
      county: "Bacon",
      pop: 9730,
    },
    {
      zip: "31512",
      city: "Ambrose",
      county: "Coffee",
      pop: 2153,
    },
    {
      zip: "31513",
      city: "Baxley",
      county: "Appling",
      pop: 16105,
    },
    {
      zip: "31516",
      city: "Blackshear",
      county: "Pierce",
      pop: 14953,
    },
    {
      zip: "31518",
      city: "Bristol",
      county: "Pierce",
      pop: 933,
    },
    {
      zip: "31519",
      city: "Broxton",
      county: "Coffee",
      pop: 3562,
    },
    {
      zip: "31520",
      city: "Brunswick",
      county: "Glynn",
      pop: 22847,
    },
    {
      zip: "31522",
      city: "Saint Simons Island",
      county: "Glynn",
      pop: 16745,
    },
    {
      zip: "31523",
      city: "Brunswick",
      county: "Glynn",
      pop: 13651,
    },
    {
      zip: "31524",
      city: "Brunswick",
      county: "Glynn",
      pop: 0,
    },
    {
      zip: "31525",
      city: "Brunswick",
      county: "Glynn",
      pop: 30257,
    },
    {
      zip: "31527",
      city: "Jekyll Island",
      county: "Glynn",
      pop: 883,
    },
    {
      zip: "31532",
      city: "Denton",
      county: "Jeff Davis",
      pop: 565,
    },
    {
      zip: "31533",
      city: "Douglas",
      county: "Coffee",
      pop: 17087,
    },
    {
      zip: "31535",
      city: "Douglas",
      county: "Coffee",
      pop: 10893,
    },
    {
      zip: "31537",
      city: "Folkston",
      county: "Charlton",
      pop: 10858,
    },
    {
      zip: "31539",
      city: "Hazlehurst",
      county: "Jeff Davis",
      pop: 14733,
    },
    {
      zip: "31542",
      city: "Hoboken",
      county: "Brantley",
      pop: 2805,
    },
    {
      zip: "31543",
      city: "Hortense",
      county: "Brantley",
      pop: 4242,
    },
    {
      zip: "31544",
      city: "Jacksonville",
      county: "Telfair",
      pop: 770,
    },
    {
      zip: "31545",
      city: "Jesup",
      county: "Wayne",
      pop: 16119,
    },
    {
      zip: "31546",
      city: "Jesup",
      county: "Wayne",
      pop: 8415,
    },
    {
      zip: "31547",
      city: "Kings Bay",
      county: "Camden",
      pop: 1262,
    },
    {
      zip: "31548",
      city: "Kingsland",
      county: "Camden",
      pop: 21680,
    },
    {
      zip: "31549",
      city: "Lumber City",
      county: "Telfair",
      pop: 2143,
    },
    {
      zip: "31550",
      city: "Manor",
      county: "Ware",
      pop: 796,
    },
    {
      zip: "31551",
      city: "Mershon",
      county: "Pierce",
      pop: 848,
    },
    {
      zip: "31552",
      city: "Millwood",
      county: "Ware",
      pop: 1194,
    },
    {
      zip: "31553",
      city: "Nahunta",
      county: "Brantley",
      pop: 4660,
    },
    {
      zip: "31554",
      city: "Nicholls",
      county: "Coffee",
      pop: 8293,
    },
    {
      zip: "31555",
      city: "Odum",
      county: "Wayne",
      pop: 2451,
    },
    {
      zip: "31556",
      city: "Offerman",
      county: "Pierce",
      pop: 94,
    },
    {
      zip: "31557",
      city: "Patterson",
      county: "Pierce",
      pop: 3296,
    },
    {
      zip: "31558",
      city: "Saint Marys",
      county: "Camden",
      pop: 21586,
    },
    {
      zip: "31560",
      city: "Screven",
      county: "Wayne",
      pop: 2448,
    },
    {
      zip: "31561",
      city: "Sea Island",
      county: "Glynn",
      pop: 47,
    },
    {
      zip: "31563",
      city: "Surrency",
      county: "Appling",
      pop: 1369,
    },
    {
      zip: "31565",
      city: "Waverly",
      county: "Camden",
      pop: 2009,
    },
    {
      zip: "31566",
      city: "Waynesville",
      county: "Brantley",
      pop: 4787,
    },
    {
      zip: "31567",
      city: "West Green",
      county: "Coffee",
      pop: 768,
    },
    {
      zip: "31568",
      city: "White Oak",
      county: "Camden",
      pop: 609,
    },
    {
      zip: "31569",
      city: "Woodbine",
      county: "Camden",
      pop: 5789,
    },
    {
      zip: "31601",
      city: "Valdosta",
      county: "Lowndes",
      pop: 30597,
    },
    {
      zip: "31602",
      city: "Valdosta",
      county: "Lowndes",
      pop: 36626,
    },
    {
      zip: "31605",
      city: "Valdosta",
      county: "Lowndes",
      pop: 23437,
    },
    {
      zip: "31606",
      city: "Valdosta",
      county: "Lowndes",
      pop: 3743,
    },
    {
      zip: "31620",
      city: "Adel",
      county: "Cook",
      pop: 10835,
    },
    {
      zip: "31622",
      city: "Alapaha",
      county: "Berrien",
      pop: 1904,
    },
    {
      zip: "31623",
      city: "Argyle",
      county: "Clinch",
      pop: 94,
    },
    {
      zip: "31624",
      city: "Axson",
      county: "Atkinson",
      pop: 1332,
    },
    {
      zip: "31625",
      city: "Barney",
      county: "Brooks",
      pop: 1008,
    },
    {
      zip: "31626",
      city: "Boston",
      county: "Thomas",
      pop: 3416,
    },
    {
      zip: "31627",
      city: "Cecil",
      county: "Cook",
      pop: 257,
    },
    {
      zip: "31629",
      city: "Dixie",
      county: "Brooks",
      pop: 956,
    },
    {
      zip: "31630",
      city: "Du Pont",
      county: "Clinch",
      pop: 448,
    },
    {
      zip: "31631",
      city: "Fargo",
      county: "Clinch",
      pop: 456,
    },
    {
      zip: "31632",
      city: "Hahira",
      county: "Lowndes",
      pop: 13483,
    },
    {
      zip: "31634",
      city: "Homerville",
      county: "Clinch",
      pop: 5726,
    },
    {
      zip: "31635",
      city: "Lakeland",
      county: "Lanier",
      pop: 6774,
    },
    {
      zip: "31636",
      city: "Lake Park",
      county: "Lowndes",
      pop: 11005,
    },
    {
      zip: "31637",
      city: "Lenox",
      county: "Cook",
      pop: 2900,
    },
    {
      zip: "31638",
      city: "Morven",
      county: "Brooks",
      pop: 1047,
    },
    {
      zip: "31639",
      city: "Nashville",
      county: "Berrien",
      pop: 9943,
    },
    {
      zip: "31641",
      city: "Naylor",
      county: "Lowndes",
      pop: 1872,
    },
    {
      zip: "31642",
      city: "Pearson",
      county: "Atkinson",
      pop: 4804,
    },
    {
      zip: "31643",
      city: "Quitman",
      county: "Brooks",
      pop: 8344,
    },
    {
      zip: "31645",
      city: "Ray City",
      county: "Berrien",
      pop: 5048,
    },
    {
      zip: "31647",
      city: "Sparks",
      county: "Cook",
      pop: 3781,
    },
    {
      zip: "31648",
      city: "Statenville",
      county: "Echols",
      pop: 828,
    },
    {
      zip: "31649",
      city: "Stockton",
      county: "Lanier",
      pop: 1091,
    },
    {
      zip: "31650",
      city: "Willacoochee",
      county: "Atkinson",
      pop: 3982,
    },
    {
      zip: "31698",
      city: "Valdosta",
      county: "Lowndes",
      pop: 744,
    },
    {
      zip: "31699",
      city: "Valdosta",
      county: "Lowndes",
      pop: 685,
    },
    {
      zip: "31701",
      city: "Albany",
      county: "Dougherty",
      pop: 18699,
    },
    {
      zip: "31705",
      city: "Albany",
      county: "Dougherty",
      pop: 31935,
    },
    {
      zip: "31707",
      city: "Albany",
      county: "Dougherty",
      pop: 25405,
    },
    {
      zip: "31709",
      city: "Americus",
      county: "Sumter",
      pop: 15802,
    },
    {
      zip: "31711",
      city: "Andersonville",
      county: "Sumter",
      pop: 715,
    },
    {
      zip: "31712",
      city: "Arabi",
      county: "Crisp",
      pop: 1056,
    },
    {
      zip: "31714",
      city: "Ashburn",
      county: "Turner",
      pop: 5533,
    },
    {
      zip: "31716",
      city: "Baconton",
      county: "Mitchell",
      pop: 3079,
    },
    {
      zip: "31720",
      city: "Barwick",
      county: "Brooks",
      pop: 237,
    },
    {
      zip: "31722",
      city: "Berlin",
      county: "Colquitt",
      pop: 473,
    },
    {
      zip: "31730",
      city: "Camilla",
      county: "Mitchell",
      pop: 8056,
    },
    {
      zip: "31733",
      city: "Chula",
      county: "Tift",
      pop: 1284,
    },
    {
      zip: "31735",
      city: "Cobb",
      county: "Sumter",
      pop: 686,
    },
    {
      zip: "31738",
      city: "Coolidge",
      county: "Thomas",
      pop: 1922,
    },
    {
      zip: "31743",
      city: "De Soto",
      county: "Sumter",
      pop: 343,
    },
    {
      zip: "31744",
      city: "Doerun",
      county: "Colquitt",
      pop: 2925,
    },
    {
      zip: "31747",
      city: "Ellenton",
      county: "Colquitt",
      pop: 196,
    },
    {
      zip: "31749",
      city: "Enigma",
      county: "Berrien",
      pop: 2825,
    },
    {
      zip: "31750",
      city: "Fitzgerald",
      county: "Ben Hill",
      pop: 17998,
    },
    {
      zip: "31756",
      city: "Hartsfield",
      county: "Colquitt",
      pop: 1000,
    },
    {
      zip: "31757",
      city: "Thomasville",
      county: "Thomas",
      pop: 10905,
    },
    {
      zip: "31763",
      city: "Leesburg",
      county: "Lee",
      pop: 24352,
    },
    {
      zip: "31764",
      city: "Leslie",
      county: "Sumter",
      pop: 1456,
    },
    {
      zip: "31765",
      city: "Meigs",
      county: "Thomas",
      pop: 2668,
    },
    {
      zip: "31768",
      city: "Moultrie",
      county: "Colquitt",
      pop: 23016,
    },
    {
      zip: "31771",
      city: "Norman Park",
      county: "Colquitt",
      pop: 6903,
    },
    {
      zip: "31772",
      city: "Oakfield",
      county: "Worth",
      pop: 518,
    },
    {
      zip: "31773",
      city: "Ochlocknee",
      county: "Thomas",
      pop: 3702,
    },
    {
      zip: "31774",
      city: "Ocilla",
      county: "Irwin",
      pop: 6831,
    },
    {
      zip: "31775",
      city: "Omega",
      county: "Tift",
      pop: 3332,
    },
    {
      zip: "31778",
      city: "Pavo",
      county: "Thomas",
      pop: 2277,
    },
    {
      zip: "31779",
      city: "Pelham",
      county: "Mitchell",
      pop: 10092,
    },
    {
      zip: "31780",
      city: "Plains",
      county: "Sumter",
      pop: 2026,
    },
    {
      zip: "31781",
      city: "Poulan",
      county: "Worth",
      pop: 2263,
    },
    {
      zip: "31783",
      city: "Rebecca",
      county: "Turner",
      pop: 932,
    },
    {
      zip: "31784",
      city: "Sale City",
      county: "Mitchell",
      pop: 885,
    },
    {
      zip: "31787",
      city: "Smithville",
      county: "Lee",
      pop: 1392,
    },
    {
      zip: "31789",
      city: "Sumner",
      county: "Worth",
      pop: 947,
    },
    {
      zip: "31790",
      city: "Sycamore",
      county: "Turner",
      pop: 2105,
    },
    {
      zip: "31791",
      city: "Sylvester",
      county: "Worth",
      pop: 11894,
    },
    {
      zip: "31792",
      city: "Thomasville",
      county: "Thomas",
      pop: 23572,
    },
    {
      zip: "31793",
      city: "Tifton",
      county: "Tift",
      pop: 9208,
    },
    {
      zip: "31794",
      city: "Tifton",
      county: "Tift",
      pop: 28119,
    },
    {
      zip: "31795",
      city: "Ty Ty",
      county: "Tift",
      pop: 1819,
    },
    {
      zip: "31796",
      city: "Warwick",
      county: "Worth",
      pop: 1082,
    },
    {
      zip: "31798",
      city: "Wray",
      county: "Irwin",
      pop: 834,
    },
    {
      zip: "31801",
      city: "Box Springs",
      county: "Talbot",
      pop: 3237,
    },
    {
      zip: "31803",
      city: "Buena Vista",
      county: "Marion",
      pop: 5317,
    },
    {
      zip: "31804",
      city: "Cataula",
      county: "Harris",
      pop: 6186,
    },
    {
      zip: "31805",
      city: "Cusseta",
      county: "Chattahoochee",
      pop: 2745,
    },
    {
      zip: "31806",
      city: "Ellaville",
      county: "Schley",
      pop: 5183,
    },
    {
      zip: "31807",
      city: "Ellerslie",
      county: "Harris",
      pop: 3167,
    },
    {
      zip: "31808",
      city: "Fortson",
      county: "Muscogee",
      pop: 7716,
    },
    {
      zip: "31810",
      city: "Geneva",
      county: "Talbot",
      pop: 212,
    },
    {
      zip: "31811",
      city: "Hamilton",
      county: "Harris",
      pop: 6442,
    },
    {
      zip: "31812",
      city: "Junction City",
      county: "Talbot",
      pop: 547,
    },
    {
      zip: "31814",
      city: "Louvale",
      county: "Stewart",
      pop: 192,
    },
    {
      zip: "31815",
      city: "Lumpkin",
      county: "Stewart",
      pop: 3889,
    },
    {
      zip: "31816",
      city: "Manchester",
      county: "Meriwether",
      pop: 5271,
    },
    {
      zip: "31820",
      city: "Midland",
      county: "Muscogee",
      pop: 11750,
    },
    {
      zip: "31821",
      city: "Omaha",
      county: "Stewart",
      pop: 267,
    },
    {
      zip: "31822",
      city: "Pine Mountain",
      county: "Harris",
      pop: 5396,
    },
    {
      zip: "31823",
      city: "Pine Mountain Valley",
      county: "Harris",
      pop: 857,
    },
    {
      zip: "31824",
      city: "Preston",
      county: "Webster",
      pop: 1567,
    },
    {
      zip: "31825",
      city: "Richland",
      county: "Stewart",
      pop: 2292,
    },
    {
      zip: "31826",
      city: "Shiloh",
      county: "Harris",
      pop: 1872,
    },
    {
      zip: "31827",
      city: "Talbotton",
      county: "Talbot",
      pop: 2194,
    },
    {
      zip: "31829",
      city: "Upatoi",
      county: "Muscogee",
      pop: 758,
    },
    {
      zip: "31830",
      city: "Warm Springs",
      county: "Meriwether",
      pop: 2558,
    },
    {
      zip: "31831",
      city: "Waverly Hall",
      county: "Harris",
      pop: 3272,
    },
    {
      zip: "31832",
      city: "Weston",
      county: "Webster",
      pop: 298,
    },
    {
      zip: "31833",
      city: "West Point",
      county: "Troup",
      pop: 7082,
    },
    {
      zip: "31836",
      city: "Woodland",
      county: "Talbot",
      pop: 953,
    },
    {
      zip: "31901",
      city: "Columbus",
      county: "Muscogee",
      pop: 6181,
    },
    {
      zip: "31903",
      city: "Columbus",
      county: "Muscogee",
      pop: 17922,
    },
    {
      zip: "31904",
      city: "Columbus",
      county: "Muscogee",
      pop: 32717,
    },
    {
      zip: "31905",
      city: "Fort Benning",
      county: "Muscogee",
      pop: 17743,
    },
    {
      zip: "31906",
      city: "Columbus",
      county: "Muscogee",
      pop: 20349,
    },
    {
      zip: "31907",
      city: "Columbus",
      county: "Muscogee",
      pop: 57967,
    },
    {
      zip: "31909",
      city: "Columbus",
      county: "Muscogee",
      pop: 39151,
    },
  ],
};
